### ISSUE TITLE
【Solved】chrome's shortcut is not working

### ISSUE THREAD

**Issue by microdockman** [tjackenpacken/taskbar-groups#121]
I made some chrome's shortcut icon and successfully added them to taskbar-groups, but nothing happened when I clicked them
![Screenshot 2021-04-29 132752](https://user-images.githubusercontent.com/31898637/116506599-2fa6a580-a8f0-11eb-857c-deb9d7e55552.jpg)

This is a desktop shortcut icon, can be opened normally
![asdasdadapture](https://user-images.githubusercontent.com/31898637/116506612-359c8680-a8f0-11eb-96e7-aa691004bb18.jpg)

This is the icon's properties page
![as22re](https://user-images.githubusercontent.com/31898637/116506859-b2c7fb80-a8f0-11eb-9af0-d5c837f0af1c.JPG)

Other types of shortcut icons work fine
e.g.
![33Capture](https://user-images.githubusercontent.com/31898637/116507127-3d105f80-a8f1-11eb-93ef-0e72df60bef1.JPG)

**Comment by JohnLGalt** [comment]
Same here.  I have created a group for browsers, as I use Firefox Nightly, Firefox stable, 2 profiles in Chrome stable and 2 profiles in Edge stable.  Both Firefox are set to open the profile manager every time via argument **-p** and they work perfectly fine.  Both Edge Profiles are set to run with arguments **--profile-directory=Default** and **--profile-directory="Profile 1"**, and they work perfectly fine.  

Both Chromes are set to run with arguments **--profile-directory=Default** and **--profile-directory="Profile 1"**, but neither works.  As direct shortcuts, the shortcuts set to run with arguments **--profile-directory=Default** and **--profile-directory="Profile 1"** both work perfectly fine.  I also tried removing the double quotation marks, but still did not work.

Using those shortcuts in BINS application (similar application from a StarDock Dev) also work perfectly fine.  Only in here do they not work.

**Comment by microdockman** [comment]
> Same here. I have created a group for browsers, as I use Firefox Nightly, Firefox stable, 2 profiles in Chrome stable and 2 profiles in Edge stable. Both Firefox are set to open the profile manager every time via argument **-p** and they work perfectly fine. Both Edge Profiles are set to run with arguments **--profile-directory=Default** and **--profile-directory="Profile 1"**, and they work perfectly fine.
> 
> Both Chromes are set to run with arguments **--profile-directory=Default** and **--profile-directory="Profile 1"**, but neither works. As direct shortcuts, the shortcuts set to run with arguments **--profile-directory=Default** and **--profile-directory="Profile 1"** both work perfectly fine. I also tried removing the double quotation marks, but still did not work.
> 
> Using those shortcuts in BINS application (similar application from a StarDock Dev) also work perfectly fine. Only in here do they not work.

Some path issues
Error message： System.IO.FileNotFoundException: C:\Program Files (x86)\Google\Chrome\Application\chrome_proxy.exe
the 32-bit version is not installed ，so this path not exist

Now I have installed the Canary version [32 or 64 bit]，and recreated the shortcut icon, it works fine after adding to taskbar-groups
# the program path becomes to "C:\Users\DeskminiA300\AppData\Local\Google\Chrome SxS\Application\chrome.exe"

https://www.google.com/intl/en/chrome/canary/
 
I don't know how to change the stable version chrome's installation path, maybe it will work

**Comment by microdockman** [comment]
> Same here. I have created a group for browsers, as I use Firefox Nightly, Firefox stable, 2 profiles in Chrome stable and 2 profiles in Edge stable. Both Firefox are set to open the profile manager every time via argument **-p** and they work perfectly fine. Both Edge Profiles are set to run with arguments **--profile-directory=Default** and **--profile-directory="Profile 1"**, and they work perfectly fine.
> 
> Both Chromes are set to run with arguments **--profile-directory=Default** and **--profile-directory="Profile 1"**, but neither works. As direct shortcuts, the shortcuts set to run with arguments **--profile-directory=Default** and **--profile-directory="Profile 1"** both work perfectly fine. I also tried removing the double quotation marks, but still did not work.
> 
> Using those shortcuts in BINS application (similar application from a StarDock Dev) also work perfectly fine. Only in here do they not work.

Some path issues
Error message： System.IO.FileNotFoundException: C:\Program Files (x86)\Google\Chrome\Application\chrome_proxy.exe
the 32-bit version is not installed ，so this path not exist

Now I have installed the Canary version [32 or 64 bit]，and recreated the shortcut icon, it works fine after adding to taskbar-groups
the program path becomes to "C:\Users\DeskminiA300\AppData\Local\Google\Chrome SxS\Application\chrome.exe"

https://www.google.com/intl/en/chrome/canary/
 
I don't know how to change the stable version chrome's installation path, maybe it will work

**Comment by JohnLGalt** [comment]
Yeah, this is a (relatively recent) change to Chrome installations:

https://www.ghacks.net/2020/06/11/google-chrome-is-soon-going-to-be-installed-in-a-different-directory-on-windows/

It used to always use %ProgramFiles(x86)% (and before that, *ProgramData%, and before that, for single user use in %UserProfile%).....

Mine exists in %ProgramFiles% which is =/= %ProgramFIles(x86)% since my OS is 64 bit.  So the code will likely need to be changed so that it looks in the location specified by the shortcut itself.

**Comment by microdockman** [comment]
> Yeah, this is a (relatively recent) change to Chrome installations:
> 
> https://www.ghacks.net/2020/06/11/google-chrome-is-soon-going-to-be-installed-in-a-different-directory-on-windows/
> 
> It used to always use %ProgramFiles(x86)% (and before that, *ProgramData%, and before that, for single user use in %UserProfile%).....
> 
> Mine exists in %ProgramFiles% which is =/= %ProgramFIles(x86)% since my OS is 64 bit. So the code will likely need to be changed so that it looks in the location specified by the shortcut itself.

It will require some tedious operation, cause headaches,, everything-default works better for me

There are also some new issues, some site's shortcuts cannot be added，Illegal character error
1 sites involving chinese characters....like jd.com
2 rarbg.com   (and this special english website)

I am not able to solve it. Looking forward to future updates

**Comment by PikeNote** [comment]
[Release.zip](https://github.com/tjackenpacken/taskbar-groups/files/6437091/Release.zip)
Sorry for the headaches! The build was set to x86 so it was looking for x86 program files by default. I had changed it in this small build change. Please test this and see if the same issue occurs.

**Comment by microdockman** [comment]
> [Release.zip](https://github.com/tjackenpacken/taskbar-groups/files/6437091/Release.zip)
> Sorry for the headaches! The build was set to x86 so it was looking for x86 program files by default. I had changed it in this small build change. Please test this and see if the same issue occurs.

【solved】
Thank you very much for your work

Another questions about chinese characters 

Like this website
https://convertio.co/en/             ok
https://convertio.co/zh/             System.Exception: The stub received bad data.     
(use chrome to make icons and add them to taskbar-groups)


![Capture](https://user-images.githubusercontent.com/31898637/117369136-148ef380-aef7-11eb-9f86-50bfdfa99f29.JPG)

Error messages will appear when adding icons via + .    (drag to add will not respond)

![Capture](https://user-images.githubusercontent.com/31898637/117370889-9e3fc080-aef9-11eb-986d-4f847f302886.JPG)

![Capture1](https://user-images.githubusercontent.com/31898637/117371035-d810c700-aef9-11eb-812d-8f67bd658a69.JPG)

**Comment by PikeNote** [comment]
Can you open a new issue for this if possible? Just easier to track issues overall. Keep this one opened though because it is not solved on master yet.

**Comment by microdockman** [comment]
> Can you open a new issue for this if possible? Just easier to track issues overall. Keep this one opened though because it is not solved on master yet.

ok, I'll open  a new issus
Thanks again for your reply

**Comment by JohnLGalt** [comment]
It's working on my end fine now.

Now, to just get Windows UWP apps working and it'll be perfect.  💯

**Comment by dzigner** [comment]
I have issues with Chrome taskbar group, in that Chrome does not open when clicked. I have similar setup with Edge, and that is working fine.

**Comment by JohnLGalt** [comment]
@dzigner

Did you use the version in [this post](https://github.com/tjackenpacken/taskbar-groups/issues/121#issuecomment-833793381) above?

**Comment by microdockman** [comment]
> Did you use the version in [this post](https://github.com/tjackenpacken/taskbar-groups/issues/121#issuecomment-833793381) above?

yes  https://github.com/tjackenpacken/taskbar-groups/files/6437091/Release.zip
Contributor recompiled  ... it works fine for me now   （chrome stable version）

**Comment by dzigner** [comment]
> @dzigner
> 
> Did you use the version in [this post](https://github.com/tjackenpacken/taskbar-groups/issues/121#issuecomment-833793381) above?

Yes, thank you for pointing that out. I downloaded, and now its working fine.
