### ISSUE TITLE
【Solved】Another questions about chinese characters

### ISSUE THREAD

**Issue by microdockman** [tjackenpacken/taskbar-groups#125]
Some site's shortcuts cannot be added  

Like this website
https://convertio.co/en/           ok  
https://convertio.co/zh/           System.Exception: The stub received bad data.  
(use chrome to make icons and add them to taskbar-groups)  

![117369136-148ef380-aef7-11eb-9f86-50bfdfa99f29](https://user-images.githubusercontent.com/31898637/117372394-04c5de00-aefc-11eb-9fa3-810657cce382.jpg)

Error messages will appear when adding icons via + . (drag to add will not respond)

![117370889-9e3fc080-aef9-11eb-986d-4f847f302886](https://user-images.githubusercontent.com/31898637/117372421-127b6380-aefc-11eb-9f95-57de91d2bdb7.jpg)

![117371035-d810c700-aef9-11eb-812d-8f67bd658a69](https://user-images.githubusercontent.com/31898637/117372450-1effbc00-aefc-11eb-9f8d-537ed36fb05e.jpg)

**Comment by PikeNote** [comment]
Actually not reproducible at the moment. Will follow up soon. What process did you use to create those shortcuts?

**Comment by microdockman** [comment]
> Actually not reproducible at the moment. Will follow up soon. What process did you use to create those shortcuts?


i can't reproduce the error too,。
I did not retry after using the new version you compiled [Release.zip](https://github.com/tjackenpacken/taskbar-groups/files/6437091/Release.zip "悬停显示")，looks like you've solved two problems at once @@

ps: taskbar-groups version: v0.2.0.0   
💯 👍
