### ISSUE TITLE
Unable to properly use

### ISSUE THREAD

**Issue by Abhijay-Tank** [tjackenpacken/taskbar-groups#138]
Some strange issue not letting me pin to taskbar

**Comment by PikeNote** [comment]
Are you able to elaborate on that?

**Comment by Abhijay-Tank** [comment]
Basically, I had made a group of Shortcuts and trying to pin it, but later i found out that the place of extraction of files was different in my system, now it is solved

**Comment by Abhijay-Tank** [comment]
How do i end the issue?
