### ISSUE TITLE
[Feature Request] Manual app organizing

### ISSUE THREAD

**Issue by GhostFace54** [tjackenpacken/taskbar-groups#14]
I usually have the apps sorted in a way that they match like shades

**Comment by tjackenpacken** [comment]
Adding better edit features to groups is definately something i will add in future releases. As of now the way you cant sort the shortcuts is by adding them to the group in the correct order. Just remember that the application will create a new row if there are more shortcuts than width

**Comment by tjackenpacken** [comment]
Sorting and editing of groups has been included in [the latest release (v0.1.4)](https://github.com/tjackenpacken/taskbar-groups/releases/tag/v0.1.4)!

**Comment by GhostFace54** [comment]
nice, thank you
