### ISSUE TITLE
When clicking on the icon in the taskbar, it opens the TaskbarGroups.exe instead of the shortcuts.

### ISSUE THREAD

**Issue by spencerkphillips** [tjackenpacken/taskbar-groups#149]
When I click on any 1 of the 3 group icons I have made and pinned, they open the shortcuts very briefly and then close. After they close, the TaskbarGroups.exe applet opens up.

I have attached a video as proof. [Video Of Issue](https://www.dropbox.com/s/90rua6vgghts1mt/TASKBAR_GROUPS.mp4?dl=0)

**Comment by PikeNote** [comment]
Hello!

Before I further look into this, can you try [this](https://github.com/PikeNote/taskbar-groups-pike-beta/releases) release?
I have forked the repo and implemented large amounts of fixes that was long overdue and it is hard to track what has been fixed or not fixed.

Please read the notice.

**Comment by spencerkphillips** [comment]
@PikeNote Thank you, that worked great!
