### ISSUE TITLE
Cannot add a VM shortcut

### ISSUE THREAD

**Issue by PadowYT2** [tjackenpacken/taskbar-groups#154]
![image](https://user-images.githubusercontent.com/71085027/123381934-04f86680-d59a-11eb-8db7-bb69a9fa71d9.png)

**Comment by PikeNote** [comment]
Related to #80 and a bunch of other issues at this moment in time.
Please refer to the build [here](https://github.com/PikeNote/taskbar-groups-pike-beta/releases) and read the notices.

**Comment by PadowYT2** [comment]
Ok, thanks
