### ISSUE TITLE
The group icon won't update.

### ISSUE THREAD

**Issue by klementchen74** [tjackenpacken/taskbar-groups#159]
I can change and save the group icon, but it won't update on the taskbar. It's still stuck on the first image I chose.

**Comment by PikeNote** [comment]
Windows limitation. I could implement something to force refresh, but that may refresh every icon and that can get a little annoying every time you change the group icon. I will see what I can do.

**Comment by klementchen74** [comment]
It fixed itself when I restarted my laptop.
