### ISSUE TITLE
[Feature Request] Allow .ico and .exe files for shortcut icon

### ISSUE THREAD

**Issue by Andrew6rant** [tjackenpacken/taskbar-groups#16]
When you choose an icon for the group, you can only use image files. I think it would be a good idea to allow you to choose a program .exe and this program would take the icon from it.
Also, I think that you should be able to use .ico icon files and Windows' built-in .dll icons

**Comment by tjackenpacken** [comment]
Support for .ico and .exe for shortcut icons has been added in [the latest release!](https://github.com/tjackenpacken/taskbar-groups/releases/tag/v0.2.0.0)
