### ISSUE TITLE
{Feature Request] Allow editing groups

### ISSUE THREAD

**Issue by Andrew6rant** [tjackenpacken/taskbar-groups#17]
Right now, you are unable to edit already-made groups, you have to delete and remake a group if you want to add another program to it.

EDIT: nvm, I saw this on the to-do list already

**Comment by Darthagnon** [comment]
Duplicate of #9

**Comment by tjackenpacken** [comment]
Sorting and editing of groups has been included in the latest release (v0.1.4)!
