### ISSUE TITLE
Certain SHORTCUT/ICON like Microsoft 365 doesn't start.

### ISSUE THREAD

**Issue by WahyuAgungBudiyanto** [tjackenpacken/taskbar-groups#179]
Hi, I have a problem. As you can see in the screenshot below I already made 1 group contains Microsoft 365, but everytime I click any icon like word, the software doesn't open.

![image](https://user-images.githubusercontent.com/73398631/134804024-dcdc4706-1ddf-4f39-aaca-5c3d212df303.png)
![image](https://user-images.githubusercontent.com/73398631/134804045-24be4150-7663-4c6d-8060-5b5fb34c482a.png)

**Comment by itsdavisdd** [comment]
same thing happening to me

**Comment by WahyuAgungBudiyanto** [comment]
> same thing happening to me

Oh man :( Is there any way to fix it?

**Comment by ArielD10** [comment]
Yes There is a way to the solution the same thing happened to me with office  but I have the solution read it in #184

**Comment by WahyuAgungBudiyanto** [comment]
@ArielD10  Thank you, I'll try it now
