### ISSUE TITLE
[Feature Request] Add Start Menu search

### ISSUE THREAD

**Issue by AwesomeIndustry** [tjackenpacken/taskbar-groups#18]
Hello,
I found that it was challenging to locate the shortuct file for each app, since they all are quite elusive and hard to find. (Also, `%appdata%` is hidden by default in the explorer and there is no way to enter a path into the file picker window) Since all start menu entries are stored in `%appdata%\Microsoft\Windows\Start Menu\Programs\`, would it be possible to add a search field to search apps in the Start Menu, instead of having to dig around and find where each app lives? (A path-entry field in the file picker would also be nice, but I'm not sure how feasible that would be).
Thanks!

**Comment by Darthagnon** [comment]
I had the same idea in #5 (closed issue). Done in commit c5dfa1aba5658b2bb29d16220193568365023580 - default starting dir for icons is My Pictures, default starting dir for programs is ```shell:appsfolder``` (special virtual folder that displays all installed programs available in the Start Menu)

**Comment by tjackenpacken** [comment]
> 
> 
> Hello,
> I found that it was challenging to locate the shortuct file for each app, since they all are quite elusive and hard to find. (Also, `%appdata%` is hidden by default in the explorer and there is no way to enter a path into the file picker window) Since all start menu entries are stored in `%appdata%\Microsoft\Windows\Start Menu\Programs\`, would it be possible to add a search field to search apps in the Start Menu, instead of having to dig around and find where each app lives? (A path-entry field in the file picker would also be nice, but I'm not sure how feasible that would be).
> Thanks!

As Darthagnon replied this has been solved already. Although i am currently investigating if it's possible to use a tweaked version of the windows "Open with..." dialog!
