### ISSUE TITLE
The Shortcuts that are in the group don't open 

### ISSUE THREAD

**Issue by ArielD10** [tjackenpacken/taskbar-groups#183]
Please Fix that i can't use it I like it but it don't open So please

**Comment by ThatCarrot** [comment]
hi. what programs are u trying to open exactly?

**Comment by Altr4f** [comment]
Hello, I have to say that it is a great program, but I have the same problem; At the beginning I only made a group of apps which were from the Microsoft Office package, but I added a program that did not detect quite well (https://physlets.org/tracker/) was present in the group only that of course faulty,
I tried to make a second group with the apps that did appear in the initial group but when clicking on them, they did not open, (word PowerPoint Excel, apps that I add to the initial group) Please fix this if possible, have a nice day

**Comment by Pr0max-nictjhfsdif** [comment]
hello, I have the same problem, there is a group, I can open it, but adobe applications do not start in it, what can I do?
