### ISSUE TITLE
[Feature Request] When launched from a shortcut anywhere, make menu appear next to it?

### ISSUE THREAD

**Issue by Darthagnon** [tjackenpacken/taskbar-groups#2]
I noticed that Taskbar Groups makes its menu appear when launched from a shortcut. When this shortcut is pinned to the taskbar, the menu pops up next to the shortcut on the taskbar.

I was wondering if it would be possible to extend this function, so that the menu appears next to any Taskbar Groups shortcut anywhere? e.g. If it had a function to create desktop shortcuts to its groups, the user opens the shortcut on the desktop, and the popup menu appears next to it (rather than just next to the taskbar).

This would make Taskbar Groups a fully-fledged replacement for the likes of Stardock Fences, or allow the user to approximate the Playstation 3 XMB on their desktop (a longtime dream of mine).

**Comment by tjackenpacken** [comment]
I think it should be a rather easy fix.

I have not been able to fetch the location of the taskbar shortcut from Windows API, so the positioning works by setting x from mouse location and y to  (Screen.PrimaryScreen.Bounds.Height - this.Height - 45).

I could add logic for if the mouse location is not 45px over the bottom of the screen

**Comment by tjackenpacken** [comment]
I made a new release that should resolve this issue: https://github.com/tjackenpacken/taskbar-groups/releases/tag/v0.2

**Comment by Darthagnon** [comment]
Thank you so much! Tested, and it's working great!
