### ISSUE TITLE
no option to save a group

### ISSUE THREAD

**Issue by robdam1001** [tjackenpacken/taskbar-groups#20]
https://imgur.com/2wA710N

No option to save newly created group with shortcuts.

**Comment by pikent** [comment]
If you minimize it, does that show anything along with resizing the window?

By the way, what is your monitor resolution?

I don't believe currently the application has dynamic re-scaling and thus at a certain resolution the application may not give you said options.

I think it is something to look into for the future.

**Comment by scabros** [comment]
exactly the same issue here, my laptop resolution is 1366*768

**Comment by scabros** [comment]
if i resize the window, it shows a scroll bar but the buttons arent there (at bottom).
also, if i press tab it switches to the buttons (so maybe it saves, maybe it cancels, etc).

**Comment by rzzzvikashkumar** [comment]
I think this is not a permanent soultion. But you can try this.
![92rjNk5aT0](https://user-images.githubusercontent.com/75368279/102921216-01ccd280-44b2-11eb-97b9-f20d4fe104b0.gif)
Simply shift your taskbar to left right. or try changing your screen resoultion.

**Comment by robdam1001** [comment]
> If you minimize it, does that show anything along with resizing the window?
> 
> By the way, what is your monitor resolution?
> 
> I don't believe currently the application has dynamic re-scaling and thus at a certain resolution the application may not give you said options.
> 
> I think it is something to look into for the future.

Minimizing changes nothing.  The resolution of my Dell XPS is 3840 x 2160.

**Comment by robdam1001** [comment]
> I think this is not a permanent soultion. But you can try this.
> ![92rjNk5aT0](https://user-images.githubusercontent.com/75368279/102921216-01ccd280-44b2-11eb-97b9-f20d4fe104b0.gif)
> Simply shift your taskbar to left right. or try changing your screen resoultion.

Your suggestion does not apply to my issue since Save and Exit are not displayed at all. Thank you.

**Comment by tjackenpacken** [comment]
> 
> 
> > If you minimize it, does that show anything along with resizing the window?
> > By the way, what is your monitor resolution?
> > I don't believe currently the application has dynamic re-scaling and thus at a certain resolution the application may not give you said options.
> > I think it is something to look into for the future.
> 
> Minimizing changes nothing. The resolution of my Dell XPS is 3840 x 2160.

Are you using any scaling on the monitor?

I am trying to recreate the issue on my computer

**Comment by pikent** [comment]
> 
> 
> > > If you minimize it, does that show anything along with resizing the window?
> > > By the way, what is your monitor resolution?
> > > I don't believe currently the application has dynamic re-scaling and thus at a certain resolution the application may not give you said options.
> > > I think it is something to look into for the future.
> > 
> > 
> > Minimizing changes nothing. The resolution of my Dell XPS is 3840 x 2160.
> 
> Are you using any scaling on the monitor?
> 
> I am trying to recreate the issue on my computer

Maybe some adjustments to the anchors anchors and setting a minimum maximum size to prevent over/under scaling. I had been testing the issue myself for a bit through just changing windows resolution to see if I can get any results currently.

**Comment by tjackenpacken** [comment]
> 
> 
> > I think this is not a permanent soultion. But you can try this.
> > ![92rjNk5aT0](https://user-images.githubusercontent.com/75368279/102921216-01ccd280-44b2-11eb-97b9-f20d4fe104b0.gif)
> > Simply shift your taskbar to left right. or try changing your screen resoultion.
> 
> Your suggestion does not apply to my issue since Save and Exit are not displayed at all. Thank you.

I have edited [the last release](https://github.com/tjackenpacken/taskbar-groups/releases/tag/v0.1.4) and updated the application to rescale. Could you try and see if it works?


> 
> 
> > > > If you minimize it, does that show anything along with resizing the window?
> > > > By the way, what is your monitor resolution?
> > > > I don't believe currently the application has dynamic re-scaling and thus at a certain resolution the application may not give you said options.
> > > > I think it is something to look into for the future.
> > > 
> > > 
> > > Minimizing changes nothing. The resolution of my Dell XPS is 3840 x 2160.
> > 
> > 
> > Are you using any scaling on the monitor?
> > I am trying to recreate the issue on my computer
> 
> Maybe some adjustments to the anchors anchors and setting a minimum maximum size to prevent over/under scaling. I had been testing the issue myself for a bit through just changing windows resolution to see if I can get any results currently.
> 
> I think it is best to set max based off of
> `Screen.PrimaryScreen.WorkingArea.Height`
> `Screen.PrimaryScreen.WorkingArea.Width`
> 
> That area should be above the taskbar. I think adding functions to stop users to drag below that point is possible.
> 
> Seems like setting bottom bar anchors to bottom left right keeps it in focus if the bottom is dragged up/down. This allows resizing of the window and keeping the edit buttons on screen.
> 
> Combining that with allowScroll seems to be able to do a temporary fix on this.

Thanks! I did the WorkingArea to set MaximumSize. But I also added some bottom anchoring and that the panel with the shortcuts starts scrolling if its bigger than a portion of the full height, rather than a fixed hight.

**Comment by robdam1001** [comment]
> > > I think this is not a permanent soultion. But you can try this.
> > > ![92rjNk5aT0](https://user-images.githubusercontent.com/75368279/102921216-01ccd280-44b2-11eb-97b9-f20d4fe104b0.gif)
> > > Simply shift your taskbar to left right. or try changing your screen resoultion.
> > 
> > 
> > Your suggestion does not apply to my issue since Save and Exit are not displayed at all. Thank you.
> 
> I have edited [the last release](https://github.com/tjackenpacken/taskbar-groups/releases/tag/v0.1.4) and updated the application to rescale. Could you try and see if it works?
> 
> > > > > If you minimize it, does that show anything along with resizing the window?
> > > > > By the way, what is your monitor resolution?
> > > > > I don't believe currently the application has dynamic re-scaling and thus at a certain resolution the application may not give you said options.
> > > > > I think it is something to look into for the future.
> > > > 
> > > > 
> > > > Minimizing changes nothing. The resolution of my Dell XPS is 3840 x 2160.
> > > 
> > > 
> > > Are you using any scaling on the monitor?
> > > I am trying to recreate the issue on my computer
> > 
> > 
> > Maybe some adjustments to the anchors anchors and setting a minimum maximum size to prevent over/under scaling. I had been testing the issue myself for a bit through just changing windows resolution to see if I can get any results currently.
> > I think it is best to set max based off of
> > `Screen.PrimaryScreen.WorkingArea.Height`
> > `Screen.PrimaryScreen.WorkingArea.Width`
> > That area should be above the taskbar. I think adding functions to stop users to drag below that point is possible.
> > Seems like setting bottom bar anchors to bottom left right keeps it in focus if the bottom is dragged up/down. This allows resizing of the window and keeping the edit buttons on screen.
> > Combining that with allowScroll seems to be able to do a temporary fix on this.
> 
> Thanks! I did the WorkingArea to set MaximumSize. But I also added some bottom anchoring and that the panel with the shortcuts starts scrolling if its bigger than a portion of the full height, rather than a fixed hight.

YES!   This works!   Thank you.

https://imgur.com/FAEnypr

**Comment by tjackenpacken** [comment]
That good to hear!
