### ISSUE TITLE
C:\programfiles...\devenve.exe pops up whenever I do anything.

### ISSUE THREAD

**Issue by CaidenKehrer** [tjackenpacken/taskbar-groups#205]
This pops up whenever I do anything with taskbar groups. Open it up -> this pops up. Add a group -> this pops up. the only group I have at the moment is a group of Visual studio 2022 and vscode

![image](https://user-images.githubusercontent.com/11600425/153628765-41514237-e85e-4550-b8d5-2cfea85d9804.png)

**Comment by hbadi** [comment]
Same here with cmake-gui.exe !
