### ISSUE TITLE
White flicker

### ISSUE THREAD

**Issue by Waleedov** [tjackenpacken/taskbar-groups#21]
![2020-12-22_11-25-04](https://user-images.githubusercontent.com/48418015/102878483-9f8bb780-4448-11eb-8ac3-994d3909e287.gif)
It works well, but visually it has an issue. Sometimes when I click on it I see a white box which makes it not perfect.

**Comment by tjackenpacken** [comment]
This issue has been resolved in [the latest release!](https://github.com/tjackenpacken/taskbar-groups/releases/tag/v0.2.0.0)
