### ISSUE TITLE
Official python Idle is not launching

### ISSUE THREAD

**Issue by ghost** [tjackenpacken/taskbar-groups#22]
I tried launching python IDLE from this tool and it does not work. But python console successfully launched from it.

https://user-images.githubusercontent.com/75368279/102903996-1d76af80-4497-11eb-8a50-6ecae2cf59c7.mp4

_I have Windows7 Ultimate SP1 Python 3.8.6._

**Comment by pikent** [comment]
Currently the program does not support shortcuts but that should change in a near-future update hopefully if it goes well.

What happens is that the program takes the target path but not the arguments. When you click, it tries to launch the target path program. The Python IDE has an argument attached referencing the IDE file. This isn't passed and thus it wouldn't work.

**Comment by tjackenpacken** [comment]
Support for .lnk shortcuts has been added in [the latest release!](https://github.com/tjackenpacken/taskbar-groups/releases/tag/v0.2.0.0)
