### ISSUE TITLE
"Could not find file ****.xml" - Where do I delete the leftovers? 

### ISSUE THREAD

**Issue by bobanilic** [tjackenpacken/taskbar-groups#236]
Whenever I try to access the TaskbarGroups folder after I moved it to a different location, I get the error message "Could not find file ****.xml".
How do I fix this? Where do I delete the leftovers?

**Comment by bobanilic** [comment]
Moving away TaskbarGroups from C:/#xx/TaskbarGroups solved the problem. Might be the symbol "#" issue.

**Comment by Michael679089** [comment]
> Moving away TaskbarGroups from C:/#xx/TaskbarGroups solved the problem. Might be the symbol "#" issue.

Is this issue solved? If it is, can you click the **closed option**. It is next to the green comment button.
