### ISSUE TITLE
[Feature-Request] Options to set background-color

### ISSUE THREAD

**Issue by xXNicksonXx** [tjackenpacken/taskbar-groups#24]
It would be nice to have 3 options to choose:

1. choose the color yourself (color-picker)
2. Take the windows accent color
3. Take the windows theme color (dark/light)

The one I would appreciate most, is the first one.

**Comment by tjackenpacken** [comment]
> 
> 
> It would be nice to have 3 options to choose:
> 
>     1. choose the color yourself (color-picker)
> 
>     2. Take the windows accent color
> 
>     3. Take the windows theme color (dark/light)
> 
> 
> The one I would appreciate most, is the first one.


This is a very good idea, and I have some plans for customization of the groups. Apart from custom colours, I'm also planning on adding custom size for the shortcuts and maybe even custom spacing between shortcuts.

As for the colour picker, do you think it would be sufficient (for starters) that the user inputs hex code or decimal code (RGB)? I could look for a more fancy color picker, but it would require more work.

Are there any other customization possibilites that would be a nice future feature?

**Comment by xXNicksonXx** [comment]
> This is a very good idea, and I have some plans for customization of the groups. Apart from custom colours, I'm also planning on adding custom size for the shortcuts and maybe even custom spacing between shortcuts.

That sounds very nice!

> As for the colour picker, do you think it would be sufficient (for starters) that the user inputs hex code or decimal code (RGB)? I could look for a more fancy color picker, but it would require more work.

For me it would be sufficient, but I dont know if everybody knows what HEX- or RGB-code is.

>Are there any other customization possibilites that would be a nice future feature?

Its not really customization, but a better hover-effect on a shortcut would be nice, than just the pointer-cursor.
Should I open a new issue for that?

**Comment by tjackenpacken** [comment]
User customization for colors and opacity has in [the latest release!](https://github.com/tjackenpacken/taskbar-groups/releases/tag/v0.2.0.0)
