### ISSUE TITLE
I cant change the icon

### ISSUE THREAD

**Issue by Mateozz02** [tjackenpacken/taskbar-groups#253]
I change the icon in the app but when i pin it to my task bar it not aplly.
![1](https://user-images.githubusercontent.com/118914618/204689602-091b81d8-c33b-4e7e-8796-e0fb8168c570.PNG)
![2](https://user-images.githubusercontent.com/118914618/204689609-db8e801c-ab77-47a7-bf76-7fecce150c5c.PNG)

**Comment by Fosternator** [comment]
Restart your computer ! 

Should fix the issue.

**Comment by Mateozz02** [comment]
It worked, thanks!!
