### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by Coding-Mole** [tjackenpacken/taskbar-groups#27]
This may sound really stupid but can I just ask, how do you use this?

**Comment by tjackenpacken** [comment]
There are no stupid questions... only bad instructions! 

1. Download the .zip-file from [the latest release](https://github.com/tjackenpacken/taskbar-groups/releases/tag/v0.1.4)
2. Pack up the .zip-file at a desired location
3. Run the TaskbarGroups.exe file in the extracted folder

When inside the client:

4. Press on the "Add taskbar group"
5. Give the group a name and an icon
6. Click on the "Add new shortcut" and select an .exe or .lnk (repeat until you got all your desired shortcuts)
7. Save
8. Left click on the group
9. In the folder that opens up, right click on the highlighted shortcut
10. Select "Pin to taskbar"

Let me know if you have any issues!

**Comment by Coding-Mole** [comment]
Thanks!!!!
