### ISSUE TITLE
Add new shortcut fot Folder

### ISSUE THREAD

**Issue by kondritsa** [tjackenpacken/taskbar-groups#29]
Please make it possible to attach not only .exe files, but also shortcuts to users folders.

**Comment by nielsd1996** [comment]
Yes, it would be nice to make groups for my ChromeApps!

**Comment by pikent** [comment]
Will consider looking into the possibly soon

**Comment by tjackenpacken** [comment]
Support for folders as shortcuts has been added in [the latest release!](https://github.com/tjackenpacken/taskbar-groups/releases/tag/v0.2.0.0)
