### ISSUE TITLE
[Bug] Initial release has no EXE icon

### ISSUE THREAD

**Issue by Darthagnon** [tjackenpacken/taskbar-groups#3]
Sorry to open 3 issues one after the other. I noticed that the EXE icon is a generic one. Would it be possible to add an icon to it?

If you like, I can make one (probably even add it using Resource Hacker).

**Comment by tjackenpacken** [comment]
No, dont be sorry, im eager for feedback!

I actually already made an icon, included it in the resources and selected it as icon through properties/application:
https://i.imgur.com/JOHjga4.png

For me the icon works if i pin the program to the taskbar. Not sure what i made wrong...

**Comment by Darthagnon** [comment]
That's odd. From your screenshot, you added the icon in the same place in Visual Studio that I have done in the past...

**Comment by Darthagnon** [comment]
@tjackenpacken I made an improved icon for Taskbar Groups - enlarged the red dot, added a black outline (so it should be more visible on white backgrounds) and a drop shadow. I also rendered a bunch more icon sizes (there were some missing from the original). I tried adding it to the EXE using Resource Hacker, but that didn't fix the icon not appearing. 
[Taskbar groups.zip](https://github.com/tjackenpacken/taskbar-groups/files/5720871/Taskbar.groups.zip)

**Comment by tjackenpacken** [comment]
> @tjackenpacken I made an improved icon for Taskbar Groups - enlarged the red dot, added a black outline (so it should be more visible on white backgrounds) and a drop shadow. I also rendered a bunch more icon sizes (there were some missing from the original). I tried adding it to the EXE using Resource Hacker, but that didn't fix the icon not appearing. 
> [Taskbar groups.zip](https://github.com/tjackenpacken/taskbar-groups/files/5720871/Taskbar.groups.zip)
> 
> Something I was wondering is the current icon looks like a sheet of paper, and more or less unrelated to the function of the program. I could draw you up a more relevant icon and post it here if you like?

The icon was actually just artwork from a game i did and used it, so you are right that it's completelty unrelated apart from the pin part. 

That would be amazing if you have the time and will! 

> 
> **Some other ideas:**
> 
> https://stackoverflow.com/questions/14704370/windows-form-icon-not-showing-in-taskbar-c-sharp
> 
> https://social.msdn.microsoft.com/Forums/windows/en-US/6dff2a76-e206-4b70-a52c-ea46ad0a6f3a/generic-icon-in-taskbar-for-c-app
> 

Thank you! Gonna look over it

**Comment by Darthagnon** [comment]
Working on the icon right now; should be ready soon. 

[BTW, you're on the news](https://www.bleepingcomputer.com/news/microsoft/new-windows-10-tool-lets-you-group-your-taskbar-shortcuts/)

**Comment by tjackenpacken** [comment]
> 
> 
> Working on the icon right now; should be ready soon.
> 
> [BTW, you're on the news](https://www.bleepingcomputer.com/news/microsoft/new-windows-10-tool-lets-you-group-your-taskbar-shortcuts/)

Oh wow!!!

**Comment by tjackenpacken** [comment]
> Here's a prototype; what do you think so far? I'm thinking I might try make a version that looks like a speech-bubble/popout window combined with a painter's palette for the 2nd attempt.

That is a great prototype! I have added it to the new [v0.1.4 release](https://github.com/tjackenpacken/taskbar-groups/releases/tag/v0.1.4)!

As the initial issue has been solved im gonna close this one. Maybe you can start a new, general icon-issue if you go for another version of the icon.
