### ISSUE TITLE
[Feature Request]Drag and drop support, different views.

### ISSUE THREAD

**Issue by Pschirki** [tjackenpacken/taskbar-groups#31]
First of all i want to thank you for this little gem here.
What i'd like do have added if possible would be:
-drag and drop support
-several views ![image](https://user-images.githubusercontent.com/70758565/103133221-8766a300-46a9-11eb-873e-e30a5409772a.png)
-

**Comment by tjackenpacken** [comment]
Drag and drop support is on its way! It's currently in the source, but has not yet reached release. So if you build it yourself you can get it now!

**Comment by Pschirki** [comment]
Great. I'll wait till the next release. Thank you very much!!
