### ISSUE TITLE
I can't find the exe file!

### ISSUE THREAD

**Issue by Abd-elrahman-Mounir** [tjackenpacken/taskbar-groups#318]
I searched and did not find anything, and I said to myself, download it anyway and follow the download steps listed in the explanation, but no matter how much I searched, I did not find the exe file.

**Comment by RohitRRao370** [comment]
that's because the link to the folder containing the exe file is in the readme, the link is a hyperlink on download and release notes

**Comment by Abd-elrahman-Mounir** [comment]
> that's because the link to the folder containing the exe file is in the readme, the link is a hyperlink on download and release notes

thank u bro ,I uploaded the wrong file, here is the correct file 
 https://github.com/tjackenpacken/taskbar-groups/releases/download/v0.2.0.0/TaskbarGroups.zip

**Comment by Abd-elrahman-Mounir** [comment]
> that's because the link to the folder containing the exe file is in the readme, the link is a hyperlink on download and release notes
