### ISSUE TITLE
[Feature Request] Add proper version information

### ISSUE THREAD

**Issue by OLLI-S** [tjackenpacken/taskbar-groups#39]
I am helping at a security tool called **VulnDetect** (it detects what applications you have installed and warns you if there are known vulnerabilities).
For VulnDetect I also programmed a little tool, that extracts the version information stored in applications.
Screenshsot: https://vulndetect.org/topic/260/toolbox-for-vulndetect

If I extract the version info from TaskbarGroups, then I get:
~~~
File name and path:     D:\PortableApps\PortableApps\_TaskbarGroups\TaskbarGroups.exe
Product Name:           main
Internal Name:          TaskbarGroups.exe
Original Filename:      TaskbarGroups.exe

File Description:       main
Company:                
Legal Copyright:        Copyright ©  2020
Legal Trademarks:       
Comments:               

File Version String:    1.0.0.0
File Version:           1.0.0.0
Product Version String: 1.0.0.0
Product Version:        1.0.0.0
~~~

The version number is totally wrong, it should be **0.1.4**.
Also the Product Name should be altered (to **TaskbarGroups**).
The other fields in the second block like File Description and Company) should also be filled.

### Reason
With the filled version information I can add TaskbarGroups to the VulnDetect database.
And also other update managers (like SUMo) benefit from the correct version info.

**Comment by tjackenpacken** [comment]
Hi!

I've made a new pull in which (I think) I have managed to add Version Number and Product Name. Could you check if it worked for your application?

**Comment by OLLI-S** [comment]
I have to admit that I used GitHuib so far to report issues.
I never used GitHuib to manage my source code (my code is locally).
Emberassing, I know....

I saw in the tab "<>Code" that you changed some files for "product name and verison string".
Here I see the changes in the code, but I did not find any new EXE file (or ZIP file containing the EXE).
I am programming in Lazarus (Pascal) not in C++ or C#, so I can not check your source code.

If you have any EXE file, I can extract the version info from it.
Or you download my tool from https://vulndetect.org/topic/260/toolbox-for-vulndetect
It is just a zipped EXE.

**Comment by tjackenpacken** [comment]
> 
> 
> I have to admit that I used GitHuib so far to report issues.
> I never used GitHuib to manage my source code (my code is locally).
> Emberassing, I know....
> 
> I saw in the tab "<>Code" that you changed some files for "product name and verison string".
> Here I see the changes in the code, but I did not find any new EXE file (or ZIP file containing the EXE).
> I am programming in Lazarus (Pascal) not in C++ or C#, so I can not check your source code.
> 
> If you have any EXE file, I can extract the version info from it.
> Or you download my tool from https://vulndetect.org/topic/260/toolbox-for-vulndetect
> It is just a zipped EXE.
> 
> **EDIT:**

If you click on the green "Code" button in the repo you find an url. You can then start Visual Studio and chose "Clone repository" and then put in the url from GitHub. 

![bild](https://user-images.githubusercontent.com/72186578/103180290-c0af3680-4894-11eb-87a9-d6a81cd4f890.png)

I am not currently on my coding machine, so I can't rebuild the solution right now my self!

**Comment by OLLI-S** [comment]
I don't have Visual Studio, I just have Lazarus, a pascal based IDE: https://www.lazarus-ide.org/
Programming like 1731, not like 2020/2021

**Comment by OLLI-S** [comment]
By the way: you also should add proper version information in the file `Config\config.exe`

**Comment by pikent** [comment]
Hello!

The config.exe application is now removed in favor of moving everything to one .exe file.
In the latest release, it is now updated to use that so only the main application needs to be changed.
I had downloaded the application myself to check out what the current version information. This is what it is currently.

```
~~~
Product Name:           TaskbarGroups
Internal Name:          TaskbarGroups.exe
Original Filename:      TaskbarGroups.exe

File Description:       TaskbarGroups
Company:                Jack Schierbeck
Legal Copyright:        Copyright ©  2020
Legal Trademarks:       
Comments:               

File Version String:    0.2.0.0
File Version:           0.2.0.0
Product Version String: 0.2.0.0
Product Version:        0.2.0.0
~~~

```

**Comment by OLLI-S** [comment]
Hello @pikent ,

the results from the Toolbox look perfect, thank you!
As soon as you release 0.2.0, I will post in the VulnDetect forums to add your tool to the database.

Yesterday I created a taskbar group called **VulnDetect**.
I also saw that you created a **VulnDetectGroup.exe** file (that was detected by SUMo, see second code block in my last posting).
If you keep these exe filed (one EXE for each group) then you should have valid version info there too.
Thank you!

OLLI

**Comment by OLLI-S** [comment]
Thank you for adding proper version info in 0.2.0.0

**Comment by OLLI-S** [comment]
@tjackenpacken just for your information; I have requested to add Taskbar Groups to the VulnDetect Database:
https://vulndetect.org/topic/982/taskbar-groups-app-request

**Comment by tjackenpacken** [comment]
That's great! Thanks
