### ISSUE TITLE
can't add steam games shortcut

### ISSUE THREAD

**Issue by scabros** [tjackenpacken/taskbar-groups#41]
hi, first thanks for your work!

when i try to add a steam game shortcut to a new group i receive a "Catastrophic failure" error.

the URI form the steam games is something like :  steam://rungameid/239350 (the only part that changes is the number)

**Comment by FordMustang0288** [comment]
This happens with Microsoft Flight Simulator from the Microsoft store too

**Comment by pikent** [comment]
I will look into it as Steam has a .url file type for its game extensions and it isn't an actual extension (.lnk) file.

As for Microsoft Flight Simulator in the Microsoft Store, how do you add the extension of an item from the Microsoft store? I need to know as to see if there is any way I can support it.

**Comment by FordMustang0288** [comment]
The msfs app has an exe extension. But there are some wonky permissions things with the folder itself. I do have a shortcut on my desktop though.

**Comment by tjackenpacken** [comment]
Support for steam apps has been added in [the latest release!](https://github.com/tjackenpacken/taskbar-groups/releases/tag/v0.2.0.0)
