### ISSUE TITLE
Unhandled Exception when not run as admin

### ISSUE THREAD

**Issue by TempestWales** [tjackenpacken/taskbar-groups#45]
Hi,

After copying the App to the Program Files folder, and running it (user is Domain User and a Local Admin) no UAC is requested, so the lack of permissions for saving a group is unhandled and the following error is generated.

![image](https://user-images.githubusercontent.com/10633668/103387085-c9547680-4af9-11eb-9145-d6f7735e0256.png)

**Comment by PikeNote** [comment]
Hello!

Thank you for the bug report! The Program Files folder does require administrator access to read from. I will implement a check and a patch for this in the near future!

**Comment by tjackenpacken** [comment]
This issue has been resolved in [the latest release!](https://github.com/tjackenpacken/taskbar-groups/releases/tag/v0.2.0.0)
