### ISSUE TITLE
There is no .exe file

### ISSUE THREAD

**Issue by JonathanCE** [tjackenpacken/taskbar-groups#47]
I have downloaded the zip file several times, it does not have any .exe file. I do not think I am doing something wrong

**Comment by PikeNote** [comment]
You can get the proper zip over [here](https://github.com/tjackenpacken/taskbar-groups/releases). When you download the zip, there should be one exe (TaskbarGroups.exe) and one folder (Config). I think you may of downloaded the zip of the entire repository.
