### ISSUE TITLE
[Feature Request] Editable starting paths?

### ISSUE THREAD

**Issue by Darthagnon** [tjackenpacken/taskbar-groups#5]
## Set starting directory to Start Menu folder?
I was really happy to find that it supported adding shortcut.lnk files, as well as EXEs.

Currently, when you click "Add new shortcut", it opens to ```C:\```. Would it be be better if, by default, it opened to ```C:\ProgramData\Microsoft\Windows\Start Menu``` (Global Start Menu shortcut folder) or ```%AppData%\Microsoft\Windows\Start Menu``` (Per-user Start Menu shortcuts)? Theoretically, every program installed on the PC should have a shortcut in one of those folders (I'm not sure which is most used, though), and it would make adding programs a bit quicker and easier.

EDIT: or just make the default directory configurable?

**Comment by Darthagnon** [comment]
## Set starting directory for "Icon repo"?

I had a brainwave, after thinking about your comment on Reddit about adding default icon packs - what about just adding configurable starting paths to Taskbar Groups, rather than wasting time and energy collecting/making icons? People will have their own icon collections; if the "Add Icon" button could open a configurable folder, then people can use their own icon packs easily.

**Comment by tjackenpacken** [comment]
> 
> ## Set starting directory to Start Menu folder?
> 
> I was really happy to find that it supported adding shortcut.lnk files, as well as EXEs.
> 
> Currently, when you click "Add new shortcut", it opens to `C:\`. Would it be be better if, by default, it opened to `C:\ProgramData\Microsoft\Windows\Start Menu` (Global Start Menu shortcut folder) or `%AppData%\Microsoft\Windows\Start Menu` (Per-user Start Menu shortcuts)? Theoretically, every program installed on the PC should have a shortcut in one of those folders (I'm not sure which is most used, though), and it would make adding programs a bit quicker and easier.
> 
> EDIT: or just make the default directory configurable?

Thanks for the suggestion! I have changed the initial directory to the global start menu folder, but i used Environment.GetFolderPath(Environment.SpecialFolder.StartMenu) as i assumed it would be more stable than a string path.

You can see the changes in the latest push of the client solution.

> 
> ## Set starting directory for "Icon repo"?
> 
> I had a brainwave, after thinking about your comment on Reddit about adding default icon packs - what about just adding configurable starting paths to Taskbar Groups, rather than wasting time and energy collecting/making icons? People will have their own icon collections; if the "Add Icon" button could open a configurable folder, then people can use their own icon packs easily.
> Path 	Current default
> Add Group Icon... 	Last accessed folder??
> Add New Shortcut 	`C:\`

I also changed the inital directory to the users My Picture folder. I think that this is sufficient for now. But I will consider extending the features of file selection in the future!

Let me know if the new push doesnt work as intended!

**Comment by Darthagnon** [comment]
That's perfect! Thank you! I saw the comment on reddit where they recommended the ```shell:appsfolder``` which I didn't even know existed.

**Comment by tjackenpacken** [comment]
> 
> 
> That's perfect! Thank you! I saw the comment on reddit where they recommended the `shell:appsfolder` which I didn't even know existed.

It doesnt seem to work very well using the `shell:appsfolder`. When opening the folder from explorer i dont get the normal right click option etc. so i guess its not the actual programs nor shortcuts found there

![bild](https://user-images.githubusercontent.com/72186578/102822041-81866e80-43d8-11eb-8379-315edb645dee.png)
