### ISSUE TITLE
[Missing feature] Ability to specify working directory and cmdline arguments

### ISSUE THREAD

**Issue by CComparon** [tjackenpacken/taskbar-groups#50]
Programs that are influenced by their initial working directory cannot be run by Taskbar Groups.
Same thing with command-line arguments.

E.g. would need to be able to specify:
```
    <ProgramShortcut>
      <FilePath>D:\tools\OBS-Studio-portable-x64\bin\64bit\obs64.exe</FilePath>
      <WorkingDir>D:\tools\OBS-Studio-portable-x64\bin\64bit</WorkingDir>
      <Arguments>
          <Argument>--portable</Argument>
          <Argument>--verbose</Argument>
          <Argument>--profile</Argument>
          <Argument>myProfile</Argument>
      </Arguments>
    </ProgramShortcut>
```

Thanks a keep up the good work!

**Comment by PikeNote** [comment]
Command line arguments were coming to version 2 but I will look to add that aswell before release. Thanks for the request!

**Comment by CComparon** [comment]
Many thanks for your quick reply.
Not a problem if they are entered as one single string, as long as spaces and escaped double-quotes are supported ;)

**Comment by tjackenpacken** [comment]
This has been added in [the latest release!](https://github.com/tjackenpacken/taskbar-groups/releases/tag/v0.2.0.0)

**Comment by CComparon** [comment]
You rock!
