### ISSUE TITLE
[Feature Request] Support for Windows Store apps

### ISSUE THREAD

**Issue by jamjnsn** [tjackenpacken/taskbar-groups#7]
The file selector does not appear to include shortcuts to Windows Store apps, which appear to be generated as special shortcut files. For example, I have a shortcut to the Spotify app from the Windows Store on my desktop, but it does not appear in the file selection dialog.

Being able to add these would be great!

**Comment by AwesomeIndustry** [comment]
I tried adding shortcuts manually from `shell:appsfolder`, but apparently they're some weird, nonstandard thing that taskbar-groups can't recognize.

**Comment by pikent** [comment]
Will be included in the next update (hopefully). Sorry for the wait!

**Comment by TheZoker** [comment]
I see that the feature was added in version 0.2.0.0.
But I'm not really sure how to add a windows store app to a group. Can you maybe explain me how to do this?
Thanks!

**Comment by PikeNote** [comment]
Sure!

First you have to search up the Windows Store App through your normal search bar after pressing the Windows Key.
Afterwards, right click the app (or on the side) and there should be a pin to start option.
Do that and the next time you press your Windows key, your page should have that new app.
Now you can drag that app directly into Taskbar Groups or you can create a shortcut and then drag that shortcut into Taskbar Groups.

**Comment by tjackenpacken** [comment]
Closing this since the issue has been resolved
