### ISSUE TITLE
Not Opening in Pinned One, Making New Instance!

### ISSUE THREAD

**Issue by hackingguy** [tjackenpacken/taskbar-groups#76]
![explorer_8pN8gCJ1A1](https://user-images.githubusercontent.com/28388650/104015553-cc76f300-51da-11eb-98b7-5d906b07c72e.png)
Whenever I **click** on a Task Bar Group, **it creates a new instance!** can't it be done within the **pinned one!**

<br><br>

![brave_852zaKNBdu](https://user-images.githubusercontent.com/28388650/104015855-3f806980-51db-11eb-8a2d-6c7d1266fbf9.png)

And **Another issue is can we handle multiple clicks**! It creates **many instances** of the same task group. It can be prevented by only allowing a single instance at a time!

**Comment by PikeNote** [comment]
It shouldn't do that. Try re-pinning the shortcut that it creates or else it may have that behavior of not stacking. If that does not work, try re-saving the group as that causes the shortcut to be recreated.

Also good point on the multiple instance issue. Will get to fixing that soon.

**Comment by hackingguy** [comment]
Just check if the process already present if yes then don't allow creating a new instance or you can use a flag file to check if the program already running.

**Comment by tjackenpacken** [comment]
I dont manage to recreate neither of the multiple instances issues you are describing here are you using the latest 2.0.0 version?

**Comment by hackingguy** [comment]
Click a group fast multiple times! this thing will surely happen!
Sometimes When I am using software that are heavy on RAM like Android Studio, it take some lag to click on taskbar group and on multiple time clicking this happens!

**Comment by hackingguy** [comment]
I think registering a small service for the program will be a better option as I feel some delay of 1-2 seconds on clicking the task bar group! I expect a smooth response as it's a small program!

**Comment by PikeNote** [comment]
That could be an option but it would still have the delay of loading the images and reading and checking shortcuts. It could be a option but I am not sure how much improvement it can have over the 1-2 second delay. I'll look further into it when I have time.
