### ISSUE TITLE
*.exe file is not included

### ISSUE THREAD

**Issue by markmelnik** [tjackenpacken/taskbar-groups#81]
It's strange, but I can't find any .exe files in downloaded archive. How can I run this utility?

**Comment by tjackenpacken** [comment]
You need to go to the [latest release](https://github.com/tjackenpacken/taskbar-groups/releases/tag/v0.2.0.0) and download the .zip file.

I just tried it myself and it worked, so im closing the issue. Let me know if it still doesnt work, and i'll reopen it.

Jack

**Comment by markmelnik** [comment]
> You need to go to the [latest release](https://github.com/tjackenpacken/taskbar-groups/releases/tag/v0.2.0.0) and download the .zip file.
> 
> I just tried it myself and it worked, so im closing the issue. Let me know if it still doesnt work, and i'll reopen it.
> 
> Jack

Yeah, I found it there. thanks for the help. Also, thanks for that utility))
