### ISSUE TITLE
[Feature Request] Add a way to edit groups

### ISSUE THREAD

**Issue by KLanausse** [tjackenpacken/taskbar-groups#9]
It would be nice if there was a way to edit groups if you want to add a newly installed program that would fit in that group or if you missed a program that you wanted to add so you wouldn't have to delete the group every time.

[Note to others: You can always edit the ObjectData.xml to add and remove programs]

**Comment by tjackenpacken** [comment]
Sorting and editing of groups has been included in [the latest release (v0.1.4)](https://github.com/tjackenpacken/taskbar-groups/releases/tag/v0.1.4)!
